### ISSUE TITLE
Website SEO

### ISSUE THREAD

**Issue by skeswa** [owlhacks/site-archive#23]
We need owlhacks.com to be the first search result when you lookup "owlhacks".

**Comment by samuelcouch** [comment]
https://developers.facebook.com/docs/plugins/checklist We should add some of this stuff.

**Comment by samuelcouch** [comment]
If someone can figure out why some of our tags aren't recognized by Facebook (mainly `og:image`) that'd be great;. I'm baffled after a few days of reading their docs looking at other site's source where they implement it successfully.

**Comment by skeswa** [comment]
This is done for the most part. We come up as the #1 in the "Owlhacks" search on Google.
