### ISSUE TITLE
Add register button to the splash

### ISSUE THREAD

**Issue by skeswa** [owlhacks/site-archive#3]

**Comment by samuelcouch** [comment]
http://apidocs.mailchimp.com/api/2.0/lists/subscribe.php 

--Probably why Mailchimp doesn't want users making their own requests. Do we want to use this for our signup? I'm not sure we need a registration just yet, but really a mailing list to be able to ping later on.

**Comment by skeswa** [comment]
Yeah, I think we should give it a go.

**Comment by samuelcouch** [comment]
I can get to this after work today.
