### ISSUE TITLE
Registration + Login + Account

### ISSUE THREAD

**Issue by skeswa** [owlhacks/site-archive#32]
Dan, Sri, Cody.

**Comment by samuelcouch** [comment]
- [ ] Registration
  - [ ] Name
  - [ ] Email (Check for .edu)
  - [ ] School
  - [ ] Shirt size
  - [ ] Food restrictions (allergies/preference)
  - [ ] First hackathon?
  - [ ] Why Owlhacks?
  - [ ] Type of hack (Hardware, software, other?)
  - [ ] Teammates
  - [ ] Resume upload
  - [ ] Github username
  - [ ] LinkedIn address
  - [ ] Twitter handle
  - [ ] Personal website
- [ ] Temple-student specific registration
  - [ ] Segregated views for administrators
- [ ] Login
  - [ ] Client-side _and_ server-side username and password checks
  - [ ] Forgot password link
- [ ] Account
  - [ ] Accepted status (Denied, Waitlist, Accepted)
    - [ ] If accepted, option to accept/decline by certain date
  - [ ]  Edit registration details

We should also discuss how to email registered people, and make sure that we have options to message _all_, _accepted_, _denied_, and _waitlisted_ --> We could build an export tool to export a CSV of emails and add it to our mailchimp list, but I'm not sure how we would go about adding the acceptance status in the mailchimp list.

**Comment by SriRamanujam** [comment]
In general, the backend is almost definitely going to be backed by a database with several views for administrators that are completely segregated from the user views. 

<h3>Authenticated views: </h3>

Administrative views: 
- [ ] Overview of all users
  - [ ] Ability to search user database by specific criteria
  - [ ] Ability to export search results directly in a variety of formats
- [ ] Individual user-level drill-down
  - [ ] Ability to edit individual user profiles
-  [ ] One-click status update: with one fell swoop we have the backend decide all our applicants' fate
- [ ] Map of applicants location geographically
- [ ] Create admin users
- [ ] Create admissions reviewer users

Admissions views:
- [ ] Page through applications
  - [ ] Page to next application
  - [ ] Page to previous application
  - [ ] Mark admitted, denied or waitlisted

User views:
- [ ] Profile overview (status, mainly)
- [ ] Password reset/change
- [ ] Profile editing

<h3>Backend functionality:</h3>

Endpoints marked with an "(A)" provide functionality exclusively for admin views
- [ ] RESTful API exposed for client communication
  - [ ] Authorized access enforced on server-side
  - Endpoints
    - [ ] Authentication (login/logout)
    - [ ] Main profile overview
    - [ ] Endpoint that shows all stored profiles (A)
    - [ ] Acceptance status (A)
    - [ ] Password reset kickoff (this endpoint should start off the password reset flow, ie, sending the email to the given email address)
    - [ ] Password reset finalize (accept new password and store in db)
    - [ ] Database search endpoint (A)
      - Implementation methods
        - [ ] Preset stored queries?
        - [ ] Serialize the variable parts of the query to be sanitized and inserted into a dynamically generated query structure on the server side? (i like this)
    - [ ] User profile editing (can be used by both users and admins)
    - [ ] Data export (A)
    - [ ] Registration/admission status update (A)
